[package]
name = "stream_digest"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
categories.workspace = true

[dependencies]
anyhow = { workspace = true }

[dev-dependencies]
tokio = { version = "1.40.0", features = ["full"] }
