[package]
name = "stream_datastore"
version = "0.1.0"
edition = "2021"
authors = ["c12i <hello@collinsmuriuki.xyz>"]

[lib]
name = "stream_datastore"
path = "./src/lib.rs"

[dependencies]
anyhow = "1.0"
chrono = "0.4.38"
rusqlite = "0.32.1"
regex = "1.10.6"

