name: Rust and Ui Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  rust-checks:
    name: Rust Checks
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    continue-on-error: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Cargo Test
        run: cargo test --no-fail-fast
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db

      - name: Rustfmt
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy -- -D warnings

  ui-checks:
    name: Typecheck, Lint, and Build
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: ./ui/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install
        working-directory: ./ui

      - name: Generate Prisma Client
        run: pnpm prisma generate
        working-directory: ./ui

      - name: Lint
        run: pnpm lint
        working-directory: ./ui

      - name: Typecheck
        run: pnpm typecheck
        working-directory: ./ui

      - name: Build
        run: pnpm build
        working-directory: ./ui
