name: Ui Workflow

on:
  push:
    branches: [main]
    paths:
      - "ui/**"
      - ".github/workflows/ui.yml"
  pull_request:
    branches: [main]
    paths:
      - "ui/**"
      - ".github/workflows/ui.yml"

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    name: Typecheck, Lint, and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Typecheck
        run: pnpm typecheck

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build
